### PR TITLE
Bug fix: to string call before the serialization could take a chance to process an object

### PR DESCRIPTION
**Pull request by acidumirae**
There is a logical bug in push & inherently publish implementations for Redis plugin.
The call to String.valueOf(row) essentially does ToString() and doing so before the serializer on the row result set basically breaks the data, renders it unusable: { column1=value1, column2=value2, ... } instead of the proper JSON format: { "column1":"value1", "column2":"value2", ... }

### CODE REVIEW

**Comment by loicmathieu** [comment]
Hi,
Thansk for the PR, can you provide a test with a JSON object to validate your change ?

**Comment by acidumirae** [comment]
> Hi, Thanks for the PR, can you provide a test with a JSON object to validate your change?

I am using it with conjunction of io.kestra.plugin.jdbc.sqlserver.Query
If you can give me a hint how I can post a POJO row set to output without the DB, then I can craft a workflow.
When using "from:" from the example it just a string and the bug is not reproducible (not a object).

**Comment by loicmathieu** [comment]
`from` is of type `object` so you can pass an arbitrary object as JSON:

```yaml
from: {"firstname": "John", "lastname": "Doe"}
```

**Comment by acidumirae** [comment]
> `from` is of type `object` so you can pass an arbitrary object as JSON:
> 
> ```yaml
> from: {"firstname": "John", "lastname": "Doe"}
> ```

Nothing gets pushed on 0.8.0-SNAPSHOT without any mods (task SUCCESS, but Count=0, Redis is empty):

```
id: redis-plugin-serialization-bug
namespace: io.kestra.demo.flows
description: Simple example of a each expression to iterate over a list of values

tasks:
  - id: redis
    type: "io.kestra.plugin.redis.ListPush"
    url: redis://:foobared@redis-queue:6479/0
    key: "test_redis_plugin"
    from: {"ID":"1000", "Id":"1000", "Value":"503410", "User_Name":"Mike Kay", "Operation":"U"}
    serdeType: JSON
```

**Comment by acidumirae** [comment]
While SQL query-based workflow works fine (minus serialization bug):

```
...
  - id: querychanges
    type: io.kestra.plugin.jdbc.sqlserver.Query
    url: jdbc:sqlserver://mssql:1433;databaseName=my_db;trustServerCertificate=true
    username: sa
    password: password
    sql: |
      SELECT ct.ID, e.Id, e.Value, e.User_Name, ct.SYS_CHANGE_OPERATION AS Operation FROM CHANGETABLE(CHANGES dbo.test, {{ outputs.querystartversionid.row.Change_Tracking_Version }}) ct LEFT JOIN dbo.test e ON e.Id = ct.ID
      WHERE (SELECT MAX(v) FROM (VALUES(ct.SYS_CHANGE_VERSION), (ct.SYS_CHANGE_CREATION_VERSION)) AS VALUE(v)) <= {{ outputs.queryendversionid.row.Change_Tracking_Current_Version }};
    store: true
  - id: redis
    type: "io.kestra.plugin.redis.ListPush"
    url: redis://:foobared@redis-queue:6479/0
    key: "test_{{ taskrun.id }}"
    from: "{{ outputs.querychanges.uri }}"
    serdeType: JSON
...
```

**Comment by acidumirae** [comment]
Ok, I got it - it is a separate problem, if the "from" IS NOT array ListPush will fail with "SUCCESS" and Count=0.
The following workflow works to reproduce the bug

````
id: redis-plugin-serialization-bug
namespace: io.kestra.demo.flows
description: Reproduce redis plugin serializatino bug

tasks:
  - id: redis
    type: "io.kestra.plugin.redis.ListPush"
    url: redis://:foobared@redis-queue:6479/0
    key: "test_redis_plugin"
    from: 
      - {"ID":"1000", "Id":"1000", "Value":"503410", "User_Name":"Mike Kay", "Operation":"U"}
      - {"ID":"999", "Id":"9999", "Value":"5034109", "User_Name":"Riki Young", "Operation":"U"}
    serdeType: JSON
```
Result in Redis https://tinypic.host/i/screenshot-2023-03-31-120121.IQEB4

```
1 | "{User_Name=Riki Young, Value=5034109, ID=999, Id=9999, Operation=U}" 
2 | "{User_Name=Mike Kay, Value=503410, ID=1000, Id=1000, Operation=U}"
```

While expected result must be:

```
1 | {"User_Name":"Riki Young", "Value":"5034109", "ID":"999", "Id":"9999", "Operation":"U"} 
2 | {"User_Name":"Mike Kay", "Value":"503410", "ID":"1000", "Id":"1000", "Operation":"U"}
```

**Comment by acidumirae** [comment]
The second issue(?) is here 
https://github.com/kestra-io/plugin-redis/blob/master/src/main/java/io/kestra/plugin/redis/ListPush.java#L69

If the "from" is not a String or a List it won't push. 
Any reason for this? 
Why don't we want to push a single object, for example?

**Comment by loicmathieu** [comment]
@acidumirae the task is a `ListPush` so it makes sense to mandate a list. It's of course possible to allow an arbitrary object but, as I said, it's called list.

Anyway there is two things missing:
- A check that if it's neither a list nor a string we throw an error
- A `@Schema(anyOf)` to document allowed values.

**Comment by loicmathieu** [comment]
@acidumirae I took your commit and open a new branch with it and added some refactoring (things changed since your opened this PR) here: #25
You're still the author of the commit ;)
I had to do this as you work directly on master so I cannot use your branch.

**Pull request closed without merging**
